name: nexthdl.build
on:
- push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly
          override: true
      - name: Build
        run: cargo build --release
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: exe
          path: target/release/concrete_execution
  concrete-test:
    name: Concrete execution test
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch binary
        uses: actions/download-artifact@v2
        with:
          name: exe
          path: exe
      - name: Run tests
        run: |
          export RUST_LOG=info
          chmod +x ./exe/concrete_execution
          /bin/time ./exe/concrete_execution ./test/concrete/fib.txt
          /bin/time ./exe/concrete_execution ./test/concrete/typefib.txt
          /bin/time ./exe/concrete_execution ./test/concrete/return_block.txt
          /bin/time ./exe/concrete_execution ./test/concrete/mksignal.txt
          /bin/time ./exe/concrete_execution ./test/symbolic/commutativity.txt
          /bin/time ./exe/concrete_execution ./test/symbolic/associativity.txt
          /bin/time ./exe/concrete_execution ./test/symbolic/if_else_simple.txt
          /bin/time ./exe/concrete_execution ./test/symbolic/if_else_inference_1.txt
          /bin/time ./exe/concrete_execution ./test/symbolic/x_logic.txt
